---
name: Continuous-Integration

on:
  push:

  workflow_dispatch:

jobs:
  ğŸ‹ docker-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ¦ˆ Linting for mintwit image
        uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: ./Docker/Dockerfiles/MiniTwitPostgres.Dockerfile
      - name: ğŸ† Linting for slimtwit image
        uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: ./Docker/Dockerfiles/SlimTwit.Dockerfile
